export type ProjectProps = {
	key: string
	title: string
	description?: string
	stack?: string[]
	bgColor: string
	metaDataStyles?: string
	imageStyles?: string
	titleStyles?: string
	href: string
	featured: boolean
	src: string
}
export const PROJECTS: ProjectProps[] = [
	{
		key: 'rara-accounting',
		title: 'RaRa Accounting Outsourcing',
		description: 'Website for a one stop accounting solutions provider agency.',
		stack: ['WordPress Design', 'Figma', 'Search Engine Optimization (SEO)', 'Web Design', 'Product Design'],
		bgColor: 'hocus:bg-green-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-green-300',
		metaDataStyles: 'group-hocus:border-green-200 dark:bg-green-900 bg-green-50',
		imageStyles: 'bg-green-50 dark:bg-opacity-[0.14] dark:bg-green-300',
		titleStyles: 'dark:group-hocus:text-green-400 group-hocus:text-green-800',
		href: 'https://raraaccountingoutsourcing.com/',
		src: 'https://raraaccountingoutsourcing.com/wp-content/uploads/2023/07/cropped-cropped-RaRa_Accounting__3_-removebg-preview-1-300x173.png',
		featured: true,
	},
	{
		key: 'komma',
		title: 'Komma',
		description: 'Creates and manages personalised investment portfolio with max returns.',
		stack: ['Product Management', 'NextJS', 'Figma', 'VueJS'],
		bgColor: 'hocus:bg-orange-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-orange-300',
		metaDataStyles: 'group-hocus:border-orange-200 dark:bg-orange-900 bg-orange-50',
		imageStyles: 'bg-orange-50 dark:bg-opacity-[0.14] dark:bg-orange-300',
		titleStyles: 'dark:group-hocus:text-orange-400 group-hocus:text-orange-800',
		href: 'https://komma.money/',
		src: 'https://komma.money/_next/image?url=%2Fkomma_logo.png&w=640&q=75',
		featured: true,
	},
	{
		key: 'induxray',
		title: 'Indu X-Ray',
		description: 'Business website for a diagnostic center in Debra, West Bengal.',
		stack: ['Wordpress Design', 'Agile Project Management', 'Figma', 'Web Design', 'Product Design'],
		bgColor: 'hocus:bg-blue-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-blue-300',
		metaDataStyles: 'group-hocus:border-blue-200 dark:bg-blue-900 bg-blue-50',
		imageStyles: 'bg-blue-50 dark:bg-opacity-[0.14] dark:bg-blue-300',
		titleStyles: 'dark:group-hocus:text-blue-400 group-hocus:text-blue-800',
		href: 'https://induxray.com/',
		src: 'https://induxray.com/wp-content/uploads/2023/09/cropped-induxray-full-logo.png',
		featured: false,
	},
	{
		key: 'amazon',
		title: 'Amazon Clone',
		description: 'A clone of Amazon home page built as a learning project.',
		stack: ['React', 'Figma'],
		bgColor: 'hocus:bg-yellow-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-yellow-300',
		metaDataStyles: 'group-hocus:border-yellow-200 dark:bg-yellow-900 bg-yellow-50',
		imageStyles: 'bg-yellow-50 dark:bg-opacity-[0.14] dark:bg-yellow-300',
		titleStyles: 'dark:group-hocus:text-yellow-400 group-hocus:text-yellow-800',
		href: 'https://agitated-noether-feb56f.netlify.app/',
		src: 'https://pngimg.com/uploads/amazon/amazon_PNG11.png',
		featured: false,
	},
	{
		key: 'netflix',
		title: 'Netflix Clone',
		description: 'A clone of Netflix home page built as a learning project.',
		stack: ['React', 'Figma'],
		bgColor: 'hocus:bg-red-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-red-300',
		metaDataStyles: 'group-hocus:border-red-200 dark:bg-red-900 bg-red-50',
		imageStyles: 'bg-red-50 dark:bg-opacity-[0.14] dark:bg-red-300',
		titleStyles: 'dark:group-hocus:text-red-400 group-hocus:text-red-800',
		href: 'https://nostalgic-lewin-7fded5.netlify.app/',
		src: 'https://assets.stickpng.com/images/580b57fcd9996e24bc43c529.png',
		featured: false,
	},
	{
		key: 'chat-app-ui-design',
		title: 'Chat App Landing Page',
		description: 'Landing page UI design of a chat app for small businesses.',
		stack: ['Figma', 'Web Design', 'Canva', 'Product Design'],
		bgColor: 'hocus:bg-blue-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-blue-300',
		metaDataStyles: 'group-hocus:border-blue-200 dark:bg-blue-900 bg-blue-50',
		imageStyles: 'bg-blue-50 dark:bg-opacity-[0.14] dark:bg-blue-300',
		titleStyles: 'dark:group-hocus:text-blue-400 group-hocus:text-blue-800',
		href: 'https://www.instagram.com/p/Cnb2s1rh7LG/',
		src: 'https://mir-s3-cdn-cf.behance.net/projects/808/34133b134136825.Y3JvcCwxMjIwLDk1NCwxMDgsMA.jpg',
		featured: false,
	},
	{
		key: 'portfolio-website-ui-design',
		title: 'Portfolio Website',
		description: 'A personal portfolio website UI design to showcase your work.',
		stack: ['Figma', 'Web Design', 'User Experience Design', 'UI Design', 'Project Management', 'Canva'],
		bgColor: 'hocus:bg-orange-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-orange-300',
		metaDataStyles: 'group-hocus:border-orange-200 dark:bg-orange-900 bg-orange-50',
		imageStyles: 'bg-orange-50 dark:bg-opacity-[0.14] dark:bg-orange-300',
		titleStyles: 'dark:group-hocus:text-orange-400 group-hocus:text-orange-800',
		href: 'https://www.instagram.com/p/CneWj-HBlwT',
		src: 'https://mir-s3-cdn-cf.behance.net/projects/808/a75805134136257.Y3JvcCw4OTEsNjk3LDEzOSww.png',
		featured: false,
	},
	{
		key: 'simplified-ecommerce-ui-design',
		title: 'Simplified ECommerce App',
		description: 'An ecommerce app providing niche products to cater a specific target audience.',
		stack: ['Product Management', 'Figma', 'User Experience Design', 'Canva', 'UI Design'],
		bgColor: 'hocus:bg-yellow-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-yellow-300',
		metaDataStyles: 'group-hocus:border-yellow-200 dark:bg-yellow-900 bg-yellow-50',
		imageStyles: 'bg-yellow-50 dark:bg-opacity-[0.14] dark:bg-yellow-300',
		titleStyles: 'dark:group-hocus:text-yellow-400 group-hocus:text-yellow-800',
		href: 'https://www.instagram.com/p/CnUi0MdBMkm/',
		src: 'https://mir-s3-cdn-cf.behance.net/projects/808/ad13f8134136729.Y3JvcCw4MDgsNjMyLDk0LDA.png',
		featured: true,
	},
	{
		key: 'growthschool-homepage-ui-design',
		title: 'Growthschool Home Page',
		description: 'Recreated Growthschool website home page as a learning project.',
		stack: ['Figma', 'Web Design', 'UI Design'],
		bgColor: 'hocus:bg-red-50 dark:hocus:bg-opacity-[0.14] dark:hocus:bg-red-300',
		metaDataStyles: 'group-hocus:border-red-200 dark:bg-red-900 bg-red-50',
		imageStyles: 'bg-red-50 dark:bg-opacity-[0.14] dark:bg-red-300',
		titleStyles: 'dark:group-hocus:text-red-400 group-hocus:text-red-800',
		href: 'https://www.instagram.com/p/Cnbaj1CrzYu/',
		src: 'https://mir-s3-cdn-cf.behance.net/projects/808/359f28160261247.Y3JvcCwyODgwLDIyNTIsMCww.png',
		featured: true,
	},
]
